name: Firebase Python Deploy Repro (Patched)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    container:
      image: python:3.11-slim
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system deps (with patched firebase-tools)
        run: |
          apt-get update
          # Node.js + npm
          apt-get install -y curl gnupg git
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs
          # Patched Firebase CLI from local tarball
          npm install -g ./firebase-tools-14.11.2.tgz

      # Authenticate to GCP with service account
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT }}

      # Create virtual environment and install dependencies
      - name: Setup Python virtual environment
        working-directory: functions
        run: |
          python3.11 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy functions (with patched CLI)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        run: |
          firebase deploy --only functions --project=${{ secrets.FIREBASE_PROJECT_ID }} --force --debug
